/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Copyright (c) 2022-2025, daeuniverse Organization <dae@v2raya.org>
 */

package domain_matcher

import (
	"fmt"
	"math/rand"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/daeuniverse/dae/common/consts"
	"github.com/sirupsen/logrus"
)

const liveGeositeFixtureEnv = "DAE_DOMAIN_MATCHER_WRITE_LIVE_FIXTURE"

func TestWriteLiveGeositeFixture(t *testing.T) {
	outPath := os.Getenv(liveGeositeFixtureEnv)
	if outPath == "" {
		t.Skipf("set %s to write live geosite matcher fixture", liveGeositeFixtureEnv)
	}

	logrus.SetLevel(logrus.WarnLevel)
	sets, err := getDomain()
	if err != nil {
		t.Fatal(err)
	}

	matcher := NewAhocorasickSlimtrie(logrus.StandardLogger(), consts.MaxMatchSetLen)
	for _, set := range sets {
		matcher.AddSet(set.RuleIndex, set.Domains, set.Key)
	}
	if err := matcher.Build(); err != nil {
		t.Fatal(err)
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# generated by TestWriteLiveGeositeFixture; do not edit by hand\n")
	fmt.Fprintf(&b, "bit_len\t%d\n", consts.MaxMatchSetLen)
	for _, set := range sets {
		for _, domain := range set.Domains {
			fmt.Fprintf(&b, "rule\t%d\t%s\t%s\n", set.RuleIndex, set.Key, domain)
		}
	}

	for _, domain := range liveGeositeFixtureDomains() {
		bitmap := matcher.MatchDomainBitmap(domain)
		words := make([]string, len(bitmap))
		for i, word := range bitmap {
			words[i] = fmt.Sprintf("%d", word)
		}
		fmt.Fprintf(&b, "case\t%s\t%s\n", domain, strings.Join(words, ","))
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		t.Fatal(err)
	}
}

func BenchmarkLiveGeositeFixtureAhocorasickSlimtrie(b *testing.B) {
	logrus.SetLevel(logrus.WarnLevel)
	sets, err := getDomain()
	if err != nil {
		b.Fatal(err)
	}

	matcher := NewAhocorasickSlimtrie(logrus.StandardLogger(), consts.MaxMatchSetLen)
	for _, set := range sets {
		matcher.AddSet(set.RuleIndex, set.Domains, set.Key)
	}
	if err := matcher.Build(); err != nil {
		b.Fatal(err)
	}

	cases := liveGeositeFixtureDomains()
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		for _, domain := range cases {
			_ = matcher.MatchDomainBitmap(domain)
		}
	}
}

func liveGeositeFixtureDomains() []string {
	rng := rand.New(rand.NewSource(300))
	cases := make([]string, 0, len(TestSample)*5)
	for _, sample := range TestSample {
		cases = append(cases, sample)
		cases = append(cases, strings.ToUpper(sample)+".")
		cases = append(cases, "api."+sample)
		if len(sample) > 3 {
			cases = append(cases, sample[1:])
		}
		addN := rng.Intn(5) + 1
		buf := make([]byte, addN)
		for i := range buf {
			buf[i] = 'a' + byte(rng.Intn('z'-'a'))
		}
		cases = append(cases, string(buf)+"."+sample)
	}
	return cases
}
